### ISSUE TITLE
sap_storage_setup: Variable fix for Simple Mount

### ISSUE THREAD

**Issue by marcelmamula** [sap-linuxlab/ansible.playbooks_for_sap#28]
@sean-freeman ENSA2 ASCS ERS Simple Mount scenario requires both ASCS and ERS file shares to be mounted on both cluster nodes, because of SAPStartSrv resource agent.

ASCS ERS Plays needs to be adjusted to account for this:
Current:
```yaml
         sap_storage_setup_nwas_abap_ascs_instance_nr: "{{ host_specifications_dictionary[sap_vm_provision_host_specification_plan]
          [inventory_hostname_short].sap_storage_setup_nwas_abap_ascs_instance_nr | default('') }}"
        sap_storage_setup_nwas_abap_ers_instance_nr: "{{ host_specifications_dictionary[sap_vm_provision_host_specification_plan]
          [inventory_hostname_short].sap_storage_setup_nwas_abap_ers_instance_nr | default('') }}"
```

Which results into issue, where cluster nodes are not aware of Instance number of other one, creating incorrect folder on NFS and mounting it incorrectly. Example for ASCS node, which does not have `sap_storage_setup_nwas_abap_ers_instance_nr` defined.
```console
/usr/sap/AE1/ASCS00
/usr/sap/AE1/ERS
```

Required cross server variable, not inside of host_specifications_dictionary:
```yaml
        sap_storage_setup_nwas_abap_ascs_instance_nr: "{{ sap_system_nwas_abap_ascs_instance_nr }}"
        sap_storage_setup_nwas_abap_ers_instance_nr: "{{ sap_system_nwas_abap_ers_instance_nr }}"
```
