### ISSUE TITLE
Interactive mode fails because of missing ./interactive/ansible_tasks_control_inputs.yml

### ISSUE THREAD

**Issue by marcelmamula** [sap-linuxlab/ansible.playbooks_for_sap#37]
### Problem
- Playbooks are searching for file that is not included in repository, neither it is mentioned in Readme.
```yaml
    - name: Playbook Interactive - Trigger prompts for VM provisioning via {{ sap_vm_provision_iac_type }}
      ansible.builtin.include_tasks: "{{ playbook_dir }}/interactive/ansible_tasks_control_inputs.yml"
      when: playbook_enable_interactive_prompts
```

### Solution
- Stat or Assert check before attempting to load from non-existent file
