### ISSUE TITLE
all: Add placeholder value detection and move sap_software_product up

### ISSUE THREAD

**Issue by marcelmamula** [sap-linuxlab/ansible.playbooks_for_sap#70]
Thank you @sean-freeman  for raising these ideas.

## 1. Add validation for placeholder values to playbook
Add simplified validation to playbook, before consuming variables that might contain placeholders. This can be simple loop over vars, similar to existing `set_fact` loop over vars.

Tested example:
```yaml
    - name: Check vars # noqa: ignore-errors
      ansible.builtin.set_fact:
        sap_playbook_placeholder_vars: "{{ sap_playbook_placeholder_vars | d([]) + [item.key] }}"
      loop: "{{ hostvars['localhost'] | dict2items | selectattr('key', 'match', '^(__)?sap_') | list }}"
      no_log: true
      ignore_errors: true
      when: item.value == 'ENTER_STRING_VALUE_HERE'

    - name: Warning
      ansible.builtin.fail:
        msg: |
          Ensure the variables do not contain placeholder values before executing playbook again.
          Variables: {{ sap_playbook_placeholder_vars | join(', ') }}
      when: sap_playbook_placeholder_vars is defined and sap_playbook_placeholder_vars | length > 0
```

## 2. Move `sap_vm_provision_dns_root_domain` from ansible_extravars.yml to platform fragments extravars.
Current placeholder `sap_vm_provision_dns_root_domain: "ENTER_STRING_VALUE_HERE"` will fail proposal 1. if it is executed on existing hosts, because they dont use it.

## 3. Move `sap_software_product` higher to section `#### Key SAP System variables ####`
Ensure that this important variable is always visible and prompts user to define it as part of other key variables.
